version: 2.1
orbs:
    ruby: circleci/ruby@0.1.2

common: &common
    steps:
        - checkout
        - run:
            name: Configure Bundler
            command: |
                echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
                source $BASH_ENV
                gem install bundler
        - restore_cache:
            keys:
                - v1-dep-bundle-{{ checksum "Gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}
        - run:
            name: Install dependencies
            command: |
                bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_cache:
            key: v1-dep-bundle-{{ checksum "Gemfile.lock" }}-{{ .Environment.CIRCLE_JOB }}
            paths:
                - vendor/bundle
        - run:
            name: Run tests
            command: |
                JETS_ENV=test bundle exec rspec --color --format documentation --format progress spec


jobs:
    "ruby-25":
        <<: *common
        docker:
            - image: cimg/ruby:2.5
              environment:
                AWS_ACCESS: 'fakeAccessKey'
                AWS_SECRET: 'fakeSecretKey'
            - image: amazon/dynamodb-local
              command: "-jar DynamoDBLocal.jar -inMemory -port 6000"
            - image: postgres
              environment:
                POSTGRES_PASSWORD: 'test'
                POSTGRES_USER: 'test'
    "ruby-26":
        <<: *common
        docker:
            - image: cimg/ruby:2.6
              environment:
                AWS_ACCESS: 'fakeAccessKey'
                AWS_SECRET: 'fakeSecretKey'
            - image: amazon/dynamodb-local
              command: "-jar DynamoDBLocal.jar -inMemory -port 6000"
            - image: postgres
              environment:
                POSTGRES_PASSWORD: 'test'
                POSTGRES_USER: 'test'
    "ruby-27":
        <<: *common
        docker:
            - image: cimg/ruby:2.7
              environment:
                AWS_ACCESS: 'fakeAccessKey'
                AWS_SECRET: 'fakeSecretKey'
            - image: amazon/dynamodb-local
              command: "-jar DynamoDBLocal.jar -inMemory -port 6000"
            - image: postgres
              environment:
                POSTGRES_PASSWORD: 'test'
                POSTGRES_USER: 'test'
workflows:
  version: 2.1
  build:
    jobs:
      - "ruby-25"
      - "ruby-26"
      - "ruby-27"