default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: 'alexgascon-api_development'
  username: 'postgres'
  password:
  host: localhost

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'alexgascon-api_development' %>

test:
  <<: *default
  database: alexgascon-api_test

production:
  <<: *default
  database: alexgascon-api_production
  url: <%= ENV['DATABASE_URL'] %>
